
- name: Add Repository
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Update packages
  apt:
    update_cache: true
      
- name: Install service
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true

- name: Setting php Timezone
  lineinfile:
    path: /etc/php/7.3/cli/php.ini
    regex: ";date.timezone ="
    line: 'date.timezone = Asia/Taipei'

- name: Setting php Timezone
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regex: ";date.timezone ="
    line: 'date.timezone = Asia/Taipei'