- name: 'Get key'
  shell: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"
  register: result
- name: print stdout
  debug:
    msg: "{{ result }}"

- name: 'Install apt-transport-https'
  shell: "sudo apt-get install apt-transport-https -y"
  register: result
- name: print stdout
  debug:
    msg: "{{ result }}"

- name: 'Input source'
  shell: "echo \"deb https://artifacts.elastic.co/packages/7.x/apt stable main\" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list"
  register: result
- name: print stdout
  debug:
    msg: "{{ result }}"

- name: 'Install metricbeat'
  shell: "sudo apt-get update && sudo apt-get install metricbeat -y"
  register: result
- name: print stdout
  debug:
    msg: "{{ result }}"

- name: 'Enable metricbeat'
  shell: "sudo systemctl enable metricbeat"
  register: result
- name: print stdout
  debug:
    msg: "{{ result }}"